#!/usr/bin/env python3
"""
Auto Programming Language File Generator Bot
Created by: Ashraf Morningstar
GitHub: https://github.com/AshrafMorningstar
Automatically creates test files for 300+ programming languages
"""

import os
import time
from datetime import datetime

class LanguageFileGenerator:
    def __init__(self):
        self.base_dir = "Programming_Languages_Test"
        self.creator_name = "Ashraf Morningstar"
        self.github_profile = "https://github.com/AshrafMorningstar"
        self.created_count = 0
        
    def create_base_structure(self):
        """Create the main directory structure"""
        if not os.path.exists(self.base_dir):
            os.makedirs(self.base_dir)
            print(f"📁 Created main directory: {self.base_dir}")
        
        # Create README with credits
        self.create_readme()
    
    def create_readme(self):
        """Create README file with credits"""
        readme_content = f"""# Programming Languages Test Files

## Auto-Generated by: {self.creator_name}
## GitHub: {self.github_profile}
## Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This repository contains test files for 300+ programming languages automatically generated by a bot.

## Purpose
- Learning different programming languages
- Testing language syntax and structure
- Reference for various programming paradigms

## Total Files Generated: {len(self.get_languages())}

---
**Auto-generated by Ashraf Morningstar's Language Generator Bot**
"""
        
        with open(os.path.join(self.base_dir, "README.md"), "w", encoding="utf-8") as f:
            f.write(readme_content)
    
    def get_languages(self):
        """Comprehensive list of 300+ programming languages with file extensions"""
        
        languages = {
            # Popular Languages
            "Python": ".py",
            "JavaScript": ".js",
            "Java": ".java",
            "C": ".c",
            "C++": ".cpp",
            "C#": ".cs",
            "PHP": ".php",
            "TypeScript": ".ts",
            "Swift": ".swift",
            "Kotlin": ".kt",
            "Go": ".go",
            "Rust": ".rs",
            "Ruby": ".rb",
            "R": ".r",
            "MATLAB": ".m",
            "Scala": ".scala",
            "Perl": ".pl",
            "Lua": ".lua",
            "Dart": ".dart",
            
            # Web Technologies
            "HTML": ".html",
            "CSS": ".css",
            "SCSS": ".scss",
            "SASS": ".sass",
            "LESS": ".less",
            "XML": ".xml",
            "JSON": ".json",
            "YAML": ".yaml",
            "Markdown": ".md",
            
            # Functional Languages
            "Haskell": ".hs",
            "Erlang": ".erl",
            "Elixir": ".ex",
            "F#": ".fs",
            "OCaml": ".ml",
            "Clojure": ".clj",
            "Scheme": ".scm",
            "Lisp": ".lisp",
            "Common Lisp": ".lisp",
            
            # Scripting Languages
            "Bash": ".sh",
            "Shell": ".sh",
            "PowerShell": ".ps1",
            "Batch": ".bat",
            "AppleScript": ".scpt",
            "AutoHotkey": ".ahk",
            "Groovy": ".groovy",
            
            # System Languages
            "Assembly": ".asm",
            "NASM": ".asm",
            "Fortran": ".f90",
            "COBOL": ".cob",
            "Pascal": ".pas",
            "Delphi": ".pas",
            "Ada": ".adb",
            
            # Database & Query Languages
            "SQL": ".sql",
            "PL/SQL": ".sql",
            "T-SQL": ".sql",
            "NoSQL": ".nosql",
            "GraphQL": ".graphql",
            
            # Mobile Development
            "Objective-C": ".m",
            "React Native": ".js",
            "Flutter": ".dart",
            "Xamarin": ".cs",
            
            # Game Development
            "Unity": ".cs",
            "Unreal Engine": ".cpp",
            "GameMaker": ".gml",
            "Godot": ".gd",
            
            # Data Science & AI
            "Julia": ".jl",
            "SAS": ".sas",
            "Stata": ".do",
            "SPSS": ".sps",
            
            # Configuration & Build
            "Dockerfile": "",
            "Makefile": "",
            "CMake": ".cmake",
            "Gradle": ".gradle",
            "Maven": ".xml",
            
            # Template Engines
            "Jinja2": ".jinja2",
            "EJS": ".ejs",
            "Handlebars": ".hbs",
            "Pug": ".pug",
            
            # More Languages
            "Prolog": ".pl",
            "Smalltalk": ".st",
            "Forth": ".fth",
            "APL": ".apl",
            "J": ".ijs",
            "Q": ".q",
            "Verilog": ".v",
            "VHDL": ".vhdl",
            "SystemVerilog": ".sv",
            
            # Modern & Emerging
            "Zig": ".zig",
            "Nim": ".nim",
            "Crystal": ".cr",
            "V": ".v",
            "Odin": ".odin",
            "Jai": ".jai",
            
            # Educational
            "Scratch": ".sb3",
            "Blockly": ".xml",
            "Logo": ".logo",
            "BASIC": ".bas",
            "QBasic": ".bas",
            
            # Esoteric
            "Brainfuck": ".bf",
            "Whitespace": ".ws",
            "Malbolge": ".mal",
            "INTERCAL": ".i",
            
            # Add 200+ more languages...
            "ActionScript": ".as",
            "AngelScript": ".as",
            "AppleScript": ".scpt",
            "Arduino": ".ino",
            "AutoIt": ".au3",
            "Awk": ".awk",
            "Ballerina": ".bal",
            "BlitzMax": ".bmx",
            "Boo": ".boo",
            "Ceylon": ".ceylon",
            "Chapel": ".chpl",
            "Cirru": ".cirru",
            "ClojureScript": ".cljs",
            "CoffeeScript": ".coffee",
            "ColdFusion": ".cfm",
            "Crystal": ".cr",
            "D": ".d",
            "Eiffel": ".e",
            "Elm": ".elm",
            "Emacs Lisp": ".el",
            "Fantom": ".fan",
            "Factor": ".factor",
            "Fancy": ".fy",
            "Fluent": ".ftl",
            "Genie": ".gs",
            "Gherkin": ".feature",
            "Golo": ".golo",
            "Gosu": ".gs",
            "Grace": ".grace",
            "Hack": ".hh",
            "Harbour": ".prg",
            "Idris": ".idr",
            "Io": ".io",
            "Ioke": ".ik",
            "Jasmine": ".js",
            "JCL": ".jcl",
            "Jython": ".py",
            "KRL": ".krl",
            "LiveScript": ".ls",
            "Mirah": ".mirah",
            "Modelica": ".mo",
            "Nemerle": ".n",
            "NetLogo": ".nlogo",
            "Nix": ".nix",
            "Nu": ".nu",
            "Oxygene": ".oxygene",
            "Oz": ".oz",
            "Pike": ".pike",
            "PogoScript": ".pogo",
            "PowerBuilder": ".pb",
            "Processing": ".pde",
            "Puppet": ".pp",
            "PureScript": ".purs",
            "Racket": ".rkt",
            "Raku": ".raku",
            "Red": ".red",
            "Ren'Py": ".rpy",
            "Ring": ".ring",
            "Roff": ".roff",
            "RPG": ".rpgle",
            "Sage": ".sage",
            "SaltStack": ".sls",
            "Self": ".self",
            "Slash": ".slash",
            "Solidity": ".sol",
            "SourcePawn": ".sp",
            "Squirrel": ".nut",
            "Standard ML": ".sml",
            "SuperCollider": ".scd",
            "Tcl": ".tcl",
            "TeX": ".tex",
            "Turing": ".t",
            "Twig": ".twig",
            "Vala": ".vala",
            "Vim script": ".vim",
            "Visual Basic": ".vb",
            "WebAssembly": ".wat",
            "Wolfram": ".wl",
            "XQuery": ".xq",
            "XSLT": ".xslt",
            "Xtend": ".xtend",
            "Yorick": ".i",
            "Zephir": ".zep",
            "Zig": ".zig",
            
            # Add even more to reach 300+
            "4D": ".4dm",
            "ABAP": ".abap",
            "ABC": ".abc",
            "ABNF": ".abnf",
            "ActionScript": ".as",
            "Ada": ".adb",
            "Adobe Font Metrics": ".afm",
            "Agda": ".agda",
            "Alloy": ".als",
            "Alpine Abuild": ".APKBUILD",
            "Altium Designer": ".OutJob",
            "AngelScript": ".as",
            "Ant Build System": ".xml",
            "ANTLR": ".g4",
            "ApacheConf": ".apacheconf",
            "Apex": ".cls",
            "API Blueprint": ".apib",
            "APL": ".apl",
            "Apollo Guidance Computer": ".agc",
            "AppleScript": ".scpt",
            "Arc": ".arc",
            "AsciiDoc": ".asciidoc",
            "ASN.1": ".asn1",
            "ASP": ".asp",
            "AspectJ": ".aj",
            "Assembly": ".asm",
            "Asymptote": ".asy",
            "ATS": ".dats",
            "Augeas": ".aug",
            "AutoHotkey": ".ahk",
            "AutoIt": ".au3",
            "Avro IDL": ".avdl",
            "Awk": ".awk",
            "Ballerina": ".bal",
            "Batchfile": ".bat",
            "Befunge": ".befunge",
            "BibTeX": ".bib",
            "Bison": ".bison",
            "BitBake": ".bb",
            "Blade": ".blade.php",
            "BlitzBasic": ".bb",
            "BlitzMax": ".bmx",
            "Bluespec": ".bsv",
            "Boo": ".boo",
            "Brainfuck": ".bf",
            "Brightscript": ".brs",
            "C-ObjDump": ".c-objdump",
            "C2hs Haskell": ".chs",
            "Cabal Config": ".cabal",
            "Cap'n Proto": ".capnp",
            "CartoCSS": ".mss",
            "Ceylon": ".ceylon",
            "Chapel": ".chpl",
            "Charity": ".ch",
            "ChucK": ".ck",
            "Cirru": ".cirru",
            "Clarion": ".clw",
            "Clean": ".icl",
            "Click": ".click",
            "CLIPS": ".clp",
            "Clojure": ".clj",
            "Closure Templates": ".soy",
            "Cloud Firestore Security Rules": ".rules",
            "CMake": ".cmake",
            "COBOL": ".cob",
            "CodeQL": ".ql",
            "CoffeeScript": ".coffee",
            "ColdFusion": ".cfm",
            "ColdFusion CFC": ".cfc",
            "COLLADA": ".dae",
            "Common Lisp": ".lisp",
            "Common Workflow Language": ".cwl",
            "Component Pascal": ".cp",
            "Cool": ".cl",
            "Coq": ".v",
            "Cpp-ObjDump": ".cpp-objdump",
            "Creole": ".creole",
            "Crystal": ".cr",
            "CSON": ".cson",
            "Csound": ".csd",
            "Csound Document": ".csd",
            "Csound Score": ".sco",
            "CSS": ".css",
            "CSV": ".csv",
            "Cuda": ".cu",
            "CWeb": ".w",
            "Cycript": ".cy",
            "Cython": ".pyx",
            "D": ".d",
            "D-ObjDump": ".d-objdump",
            "Dafny": ".dfy",
            "Darcs Patch": ".darcspatch",
            "Dart": ".dart",
            "DataWeave": ".dwl",
            "Dhall": ".dhall",
            "Diff": ".diff",
            "DIGITAL Command Language": ".com",
            "dircolors": ".dircolors",
            "DirectX 3D File": ".x",
            "DM": ".dm",
            "DNS Zone": ".zone",
            "Dockerfile": "Dockerfile",
            "Dogescript": ".djs",
            "DTrace": ".d",
            "Dylan": ".dylan",
            "E": ".e",
            "Eagle": ".sch",
            "Easybuild": ".eb",
            "EBNF": ".ebnf",
            "eC": ".ec",
            "Ecere Projects": ".epj",
            "ECL": ".ecl",
            "ECLiPSe": ".ecl",
            "EditorConfig": ".editorconfig",
            "Edje Data Collection": ".edc",
            "Eiffel": ".e",
            "EJS": ".ejs",
            "Elixir": ".ex",
            "Elm": ".elm",
            "Emacs Lisp": ".el",
            "EmberScript": ".em",
            "EQ": ".eq",
            "Erlang": ".erl",
            "F#": ".fs",
            "F*": ".fst",
            "Factor": ".factor",
            "Fancy": ".fy",
            "Fantom": ".fan",
            "Faust": ".dsp",
            "Filebench WML": ".f",
            "Filterscript": ".fs",
            "fish": ".fish",
            "FLUX": ".fx",
            "Formatted": ".for",
            "Forth": ".fth",
            "Fortran": ".f90",
            "Fortran Free Form": ".f90",
            "FreeMarker": ".ftl",
            "Frege": ".fr",
            "Futhark": ".fut",
            "G-code": ".gcode",
            "Game Maker Language": ".gml",
            "GAML": ".gaml",
            "GAMS": ".gms",
            "GAP": ".gap",
            "GCC Machine Description": ".md",
            "GDB": ".gdb",
            "GDScript": ".gd",
            "Genie": ".gs",
            "Genshi": ".kid",
            "Gentoo Ebuild": ".ebuild",
            "Gentoo Eclass": ".eclass",
            "Gerber Image": ".gbr",
            "Gettext Catalog": ".po",
            "Gherkin": ".feature",
            "Git Attributes": ".gitattributes",
            "Git Config": ".gitconfig",
            "GLSL": ".glsl",
            "Glyph": ".glf",
            "Glyph Bitmap Distribution Format": ".bdf",
            "GN": ".gn",
            "Gnuplot": ".plt",
            "Go": ".go",
            "Golo": ".golo",
            "Gosu": ".gs",
            "Grace": ".grace",
            "Gradle": ".gradle",
            "Grammatical Framework": ".gf",
            "Graph Modeling Language": ".gml",
            "GraphQL": ".graphql",
            "Graphviz (DOT)": ".dot",
            "Groovy": ".groovy",
            "Groovy Server Pages": ".gsp",
            "Hack": ".hh",
            "Haml": ".haml",
            "Handlebars": ".hbs",
            "HAProxy": ".cfg",
            "Harbour": ".prg",
            "Haskell": ".hs",
            "Haxe": ".hx",
            "HCL": ".hcl",
            "HiveQL": ".hql",
            "HLSL": ".hlsl",
            "HolyC": ".hc",
            "HTML": ".html",
            "HTML+Django": ".html",
            "HTML+ECR": ".html",
            "HTML+EEX": ".html",
            "HTML+ERB": ".html",
            "HTML+PHP": ".html",
            "HTML+Razor": ".cshtml",
            "HTTP": ".http",
            "HXML": ".hxml",
            "Hy": ".hy",
            "HyPhy": ".bf",
            "IDL": ".pro",
            "Idris": ".idr",
            "IGOR Pro": ".ipf",
            "Inform 7": ".ni",
            "INI": ".ini",
            "Inno Setup": ".iss",
            "Io": ".io",
            "Ioke": ".ik",
            "IRC log": ".irclog",
            "Isabelle": ".thy",
            "Isabelle ROOT": ".ROOT",
            "J": ".ijs",
            "Jasmin": ".j",
            "Java": ".java",
            "Java Properties": ".properties",
            "Java Server Pages": ".jsp",
            "JavaScript": ".js",
            "JavaScript+ERB": ".js",
            "JFlex": ".flex",
            "Jison": ".jison",
            "Jison Lex": ".jisonlex",
            "Jolie": ".ol",
            "JSON": ".json",
            "JSON with Comments": ".json",
            "JSON5": ".json5",
            "JSONiq": ".jq",
            "JSONLD": ".jsonld",
            "Jsonnet": ".jsonnet",
            "JSX": ".jsx",
            "Julia": ".jl",
            "Jupyter Notebook": ".ipynb",
            "Kaitai Struct": ".ksy",
            "KiCad Layout": ".kicad_pcb",
            "KiCad Legacy Layout": ".brd",
            "KiCad Schematic": ".sch",
            "Kit": ".kit",
            "Kotlin": ".kt",
            "KRL": ".krl",
            "LabVIEW": ".lvproj",
            "Lasso": ".lasso",
            "Latte": ".latte",
            "Lean": ".lean",
            "Less": ".less",
            "Lex": ".l",
            "LFE": ".lfe",
            "LilyPond": ".ly",
            "Limbo": ".b",
            "Linker Script": ".ld",
            "Linux Kernel Module": ".mod",
            "Liquid": ".liquid",
            "Literate Agda": ".lagda",
            "Literate CoffeeScript": ".litcoffee",
            "Literate Haskell": ".lhs",
            "LiveScript": ".ls",
            "LLVM": ".ll",
            "Logos": ".x",
            "Logtalk": ".lgt",
            "LOLCODE": ".lol",
            "LookML": ".lookml",
            "LoomScript": ".ls",
            "LSL": ".lsl",
            "LTspice Symbol": ".asy",
            "Lua": ".lua",
            "M": ".mumps",
            "M4": ".m4",
            "M4Sugar": ".m4",
            "Macaulay2": ".m2",
            "Makefile": "Makefile",
            "Mako": ".mako",
            "Markdown": ".md",
            "Marko": ".marko",
            "Mask": ".mask",
            "Mathematica": ".nb",
            "MATLAB": ".m",
            "Maven POM": ".xml",
            "Max": ".maxpat",
            "MAXScript": ".ms",
            "mcfunction": ".mcfunction",
            "MediaWiki": ".mediawiki",
            "Mercury": ".m",
            "Meson": ".meson.build",
            "Metal": ".metal",
            "Microsoft Developer Studio Project": ".dsp",
            "MiniD": ".minid",
            "Mirah": ".mirah",
            "Modelica": ".mo",
            "Modula-2": ".mod",
            "Modula-3": ".m3",
            "Module Management System": ".mms",
            "Monkey": ".monkey",
            "Moocode": ".moo",
            "MoonScript": ".moon",
            "Motorola 68K Assembly": ".asm",
            "MQL4": ".mq4",
            "MQL5": ".mq5",
            "MTML": ".mtml",
            "MUF": ".muf",
            "mupad": ".mn",
            "Myghty": ".myt",
            "NASL": ".nasl",
            "NCL": ".ncl",
            "Nearley": ".ne",
            "Nemerle": ".n",
            "nesC": ".nc",
            "NetLinx": ".axs",
            "NetLinx+ERB": ".axs",
            "NetLogo": ".nlogo",
            "NewLisp": ".nl",
            "Nextflow": ".nf",
            "Nginx": ".nginxconf",
            "Nim": ".nim",
            "Ninja": ".ninja",
            "Nit": ".nit",
            "Nix": ".nix",
            "NL": ".nl",
            "NSIS": ".nsi",
            "Nu": ".nu",
            "NumPy": ".numpy",
            "ObjDump": ".objdump",
            "Object Data Instance Notation": ".odin",
            "Objective-C": ".m",
            "Objective-C++": ".mm",
            "Objective-J": ".j",
            "ObjectScript": ".cls",
            "OCaml": ".ml",
            "Omgrofl": ".omgrofl",
            "ooc": ".ooc",
            "Opa": ".opa",
            "Opal": ".opal",
            "Open Policy Agent": ".rego",
            "OpenCL": ".cl",
            "OpenEdge ABL": ".p",
            "OpenQASM": ".qasm",
            "OpenRC runscript": ".run",
            "OpenSCAD": ".scad",
            "OpenStep Property List": ".plist",
            "OpenType Feature File": ".fea",
            "Org": ".org",
            "Ox": ".ox",
            "Oxygene": ".oxygene",
            "Oz": ".oz",
            "P4": ".p4",
            "Pan": ".pan",
            "Papyrus": ".psc",
            "Parrot": ".pir",
            "Parrot Assembly": ".pasm",
            "Parrot Internal Representation": ".pir",
            "Pascal": ".pas",
            "Pawn": ".pwn",
            "Pep8": ".pep",
            "Perl": ".pl",
            "PHP": ".php",
            "Pic": ".pic",
            "Pickle": ".pkl",
            "PicoLisp": ".l",
            "PigLatin": ".pig",
            "Pike": ".pike",
            "PLpgSQL": ".sql",
            "PLSQL": ".sql",
            "Pod": ".pod",
            "Pod 6": ".pod6",
            "PogoScript": ".pogo",
            "Pony": ".pony",
            "PostCSS": ".pcss",
            "PostScript": ".ps",
            "POV-Ray SDL": ".pov",
            "PowerBuilder": ".pbl",
            "PowerShell": ".ps1",
            "Processing": ".pde",
            "Proguard": ".pro",
            "Prolog": ".pl",
            "Propeller Spin": ".spin",
            "Protocol Buffer": ".proto",
            "Public Key": ".pub",
            "Pug": ".pug",
            "Puppet": ".pp",
            "Pure Data": ".pd",
            "PureBasic": ".pb",
            "PureScript": ".purs",
            "Python": ".py",
            "Python console": ".py",
            "Python traceback": ".pytb",
            "q": ".q",
            "Q#": ".qs",
            "QMake": ".pro",
            "QML": ".qml",
            "Quake": ".qc",
            "R": ".r",
            "Racket": ".rkt",
            "Ragel": ".rl",
            "Raku": ".raku",
            "RAML": ".raml",
            "Rascal": ".rsc",
            "Raw token data": ".raw",
            "RDoc": ".rdoc",
            "Readline Config": ".inputrc",
            "REALbasic": ".rbbas",
            "Reason": ".re",
            "Rebol": ".r",
            "Red": ".red",
            "Redcode": ".cw",
            "Regular Expression": ".regex",
            "Ren'Py": ".rpy",
            "RenderScript": ".rs",
            "reStructuredText": ".rst",
            "REXX": ".rexx",
            "RHTML": ".rhtml",
            "Rich Text Format": ".rtf",
            "Ring": ".ring",
            "Riot": ".tag",
            "RobotFramework": ".robot",
            "Roff": ".roff",
            "Roff Manpage": ".1",
            "Rouge": ".rg",
            "RPC": ".x",
            "RPM Spec": ".spec",
            "Ruby": ".rb",
            "RUNOFF": ".run",
            "Rust": ".rs",
            "Sage": ".sage",
            "SaltStack": ".sls",
            "SAS": ".sas",
            "Sass": ".sass",
            "Scala": ".scala",
            "Scaml": ".scaml",
            "Scheme": ".scm",
            "Scilab": ".sci",
            "SCSS": ".scss",
            "Sed": ".sed",
            "Self": ".self",
            "ShaderLab": ".shader",
            "Shell": ".sh",
            "ShellSession": ".sh-session",
            "Shen": ".shen",
            "Sieve": ".sieve",
            "Slash": ".slash",
            "Slice": ".ice",
            "Slim": ".slim",
            "Smali": ".smali",
            "Smalltalk": ".st",
            "Smarty": ".tpl",
            "SMT": ".smt",
            "Solidity": ".sol",
            "SourcePawn": ".sp",
            "SPARQL": ".rq",
            "Spline Font Database": ".sfd",
            "SQF": ".sqf",
            "SQL": ".sql",
            "SQLPL": ".sql",
            "Squirrel": ".nut",
            "SRecode Template": ".srt",
            "Stan": ".stan",
            "Standard ML": ".sml",
            "Stata": ".do",
            "STON": ".ston",
            "Stylus": ".styl",
            "SubRip Text": ".srt",
            "SugarSS": ".sss",
            "SuperCollider": ".scd",
            "SVG": ".svg",
            "Swift": ".swift",
            "SystemVerilog": ".sv",
            "Tcl": ".tcl",
            "Tcsh": ".tcsh",
            "Tea": ".tea",
            "Terra": ".t",
            "TeX": ".tex",
            "Text": ".txt",
            "Textile": ".textile",
            "Thrift": ".thrift",
            "TI Program": ".8xp",
            "TLA": ".tla",
            "TOML": ".toml",
            "Turing": ".t",
            "Turtle": ".ttl",
            "Twig": ".twig",
            "TXL": ".txl",
            "Type Language": ".tl",
            "TypeScript": ".ts",
            "Unified Parallel C": ".upc",
            "Unity3D Asset": ".asset",
            "Unix Assembly": ".s",
            "Uno": ".uno",
            "UnrealScript": ".uc",
            "UrWeb": ".ur",
            "V": ".v",
            "Vala": ".vala",
            "VBA": ".vba",
            "VBScript": ".vbs",
            "VCL": ".vcl",
            "Verilog": ".v",
            "VHDL": ".vhdl",
            "Vim script": ".vim",
            "Vim Snippet": ".snip",
            "Visual Basic": ".vb",
            "Volt": ".volt",
            "Vue": ".vue",
            "Wavefront Material": ".mtl",
            "Wavefront Object": ".obj",
            "wdl": ".wdl",
            "Web Ontology Language": ".owl",
            "WebAssembly": ".wat",
            "WebIDL": ".webidl",
            "WebVTT": ".vtt",
            "Wget Config": ".wgetrc",
            "Windows Registry Entries": ".reg",
            "wisp": ".wisp",
            "Wollok": ".wlk",
            "World of Warcraft Addon Data": ".toc",
            "X BitMap": ".xbm",
            "X Font Directory Index": ".dir",
            "X PixMap": ".xpm",
            "X10": ".x10",
            "xBase": ".prg",
            "XC": ".xc",
            "XCompose": ".compose",
            "XML": ".xml",
            "XML Property List": ".plist",
            "Xojo": ".xojo",
            "XPages": ".xsp",
            "XProc": ".xpl",
            "XQuery": ".xq",
            "XS": ".xs",
            "XSLT": ".xslt",
            "Xtend": ".xtend",
            "Yacc": ".y",
            "YAML": ".yml",
            "YANG": ".yang",
            "YARA": ".yar",
            "YASnippet": ".yasnippet",
            "ZAP": ".zap",
            "Zeek": ".zeek",
            "ZenScript": ".zs",
            "Zephir": ".zep",
            "Zig": ".zig",
            "ZIL": ".zil",
            "Zimpl": ".zimpl"
        }
        
        unique_languages = {}
        for lang, ext in languages.items():
            if lang not in unique_languages:
                unique_languages[lang] = ext
        return unique_languages
    
    def get_file_content(self, language, extension):
        """Generate appropriate content for each programming language"""
        base_comment = f"// {language} Test File\n// Auto-generated by {self.creator_name}\n// GitHub: {self.github_profile}\n// Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        
        # Language-specific templates
        templates = {
            ".py": f'"""{language} Test File\nAuto-generated by {self.creator_name}\nGitHub: {self.github_profile}\nCreated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n"""\n\nprint("Hello from {language}!")\n\n# Basic function example\ndef hello_world():\n    return "Hello, World!"\n\n# Main execution\nif __name__ == "__main__":\n    print(hello_world())',
            
            ".js": f'{base_comment}// Simple {language} example\nconsole.log("Hello from {language}!");\n\n// Function example\nfunction helloWorld() {{\n    return "Hello, World!";\n}}\n\n// Arrow function\nconst greet = (name) => `Hello, ${{name}}!`;\n\n// Usage\nconsole.log(helloWorld());\nconsole.log(greet("Developer"));',
            
            ".java": f'{base_comment}public class {language.replace(" ", "").replace("#", "Sharp")}Test {{\n    public static void main(String[] args) {{\n        System.out.println("Hello from {language}!");\n        \n        // Method call\n        String message = helloWorld();\n        System.out.println(message);\n    }}\n    \n    public static String helloWorld() {{\n        return "Hello, World!";\n    }}\n}}',
            
            ".html": f'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>{language} Test File</title>\n    <!-- Auto-generated by {self.creator_name} -->\n    <!-- GitHub: {self.github_profile} -->\n    <!-- Created: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} -->\n</head>\n<body>\n    <h1>Hello from {language}!</h1>\n    <p>This is a test file for {language}.</p>\n    \n    <script>\n        console.log("{language} file loaded successfully!");\n    </script>\n</body>\n</html>',
            
            ".cpp": f'{base_comment}#include <iostream>\n#include <string>\n\nusing namespace std;\n\nstring helloWorld() {{\n    return "Hello, World!";\n}}\n\nint main() {{\n    cout << "Hello from {language}!" << endl;\n    cout << helloWorld() << endl;\n    return 0;\n}}',
            
            ".cs": f'{base_comment}using System;\n\nnamespace {language.replace(" ", "").replace("#", "Sharp")}Test\n{{\n    class Program\n    {{\n        static void Main(string[] args)\n        {{\n            Console.WriteLine("Hello from {language}!");\n            Console.WriteLine(HelloWorld());\n        }}\n        \n        static string HelloWorld()\n        {{\n            return "Hello, World!";\n        }}\n    }}\n}}',
            
            ".php": f'<?php\n/**\n * {language} Test File\n * Auto-generated by {self.creator_name}\n * GitHub: {self.github_profile}\n * Created: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n */\n\necho "Hello from {language}!\\n";\n\nfunction helloWorld() {{\n    return "Hello, World!";\n}}\n\n// Function call\n$message = helloWorld();\necho $message . "\\n";\n\n?>',
            
            ".rb": f'{base_comment}# Simple {language} example\nputs "Hello from {language}!"\n\ndef hello_world\n  "Hello, World!"\nend\n\n# Method call\nmessage = hello_world\nputs message',
            
            ".go": f'{base_comment}package main\n\nimport "fmt"\n\nfunc helloWorld() string {{\n    return "Hello, World!"\n}}\n\nfunc main() {{\n    fmt.Println("Hello from {language}!")\n    fmt.Println(helloWorld())\n}}',
            
            ".rs": f'{base_comment}fn main() {{\n    println!("Hello from {language}!");\n    println!("{{}}", hello_world());\n}}\n\nfn hello_world() -> &\'static str {{\n    "Hello, World!"\n}}',
            
            ".ts": f'{base_comment}// TypeScript example\nconsole.log("Hello from {language}!");\n\nfunction helloWorld(): string {{\n    return "Hello, World!";\n}}\n\nconst greet = (name: string): string => `Hello, ${{name}}!`;\n\n// Usage\nconsole.log(helloWorld());\nconsole.log(greet("TypeScript Developer"));',
            
            ".sh": f'#!/bin/bash\n# {language} Test File\n# Auto-generated by {self.creator_name}\n# GitHub: {self.github_profile}\n# Created: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n\necho "Hello from {language}!"\n\nhello_world() {{\n    echo "Hello, World!"\n}}\n\n# Function call\nhello_world',
            
            ".sql": f'-- {language} Test File\n-- Auto-generated by {self.creator_name}\n-- GitHub: {self.github_profile}\n-- Created: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n\n-- Simple SQL example\nSELECT \'Hello from {language}!\' AS greeting;\n\n-- Create a simple table example\n/*\nCREATE TABLE test_table (\n    id INT PRIMARY KEY,\n    name VARCHAR(50)\n);\n*/',
            
            ".css": f'/* {language} Test File\n   Auto-generated by {self.creator_name}\n   GitHub: {self.github_profile}\n   Created: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} */\n\nbody {{\n    font-family: Arial, sans-serif;\n    margin: 0;\n    padding: 20px;\n    background-color: #f0f0f0;\n}}\n\n.container {{\n    max-width: 800px;\n    margin: 0 auto;\n    background: white;\n    padding: 20px;\n    border-radius: 8px;\n}}',
            
            ".xml": f'<?xml version="1.0" encoding="UTF-8"?>\n<!-- {language} Test File -->\n<!-- Auto-generated by {self.creator_name} -->\n<!-- GitHub: {self.github_profile} -->\n<!-- Created: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} -->\n<root>\n    <greeting>Hello from {language}!</greeting>\n    <description>This is a test XML file for {language}</description>\n</root>'
        }
        
        # Default template for unknown extensions
        default_template = f'{base_comment}// This is a test file for {language}\n// File extension: {extension}\n// Auto-generated by {self.creator_name}\n\nmain_function() {{\n    print("Hello from {language}!");\n    return "Hello, World!";\n}}\n\n// Execute\nmain_function();'
        
        return templates.get(extension, default_template)
    
    def create_language_files(self):
        """Create files for all programming languages"""
        languages = self.get_languages()
        total_languages = len(languages)
        
        print(f"🚀 Starting to create {total_languages} programming language files...")
        print(f"📁 Output directory: {self.base_dir}/")
        print("⏳ This may take a few moments...\n")
        
        start_time = time.time()
        
        for language, extension in languages.items():
            try:
                # Create filename
                if extension:
                    filename = f"test_{language.replace(' ', '_').replace('+', 'Plus').replace('#', 'Sharp')}{extension}"
                else:
                    filename = language
                
                filepath = os.path.join(self.base_dir, filename)
                
                # Get file content
                content = self.get_file_content(language, extension)
                
                # Write file
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                
                self.created_count += 1
                print(f"✅ Created: {filename}")
                
            except Exception as e:
                print(f"❌ Error creating {language}: {str(e)}")
        
        end_time = time.time()
        duration = end_time - start_time
        
        print(f"\n🎉 Successfully created {self.created_count}/{total_languages} files!")
        print(f"⏱️  Total time: {duration:.2f} seconds")
        print(f"📊 Average: {duration/total_languages:.3f} seconds per file")
    
    def generate_summary(self):
        """Generate a summary file"""
        summary_content = f"""# Programming Languages Summary

## Generated by: {self.creator_name}
## GitHub: {self.github_profile}
## Generation Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Statistics:
- Total Languages: {len(self.get_languages())}
- Successfully Created: {self.created_count}
- Success Rate: {(self.created_count/len(self.get_languages()))*100:.1f}%

## Languages Included:
"""
        
        for language, extension in self.get_languages().items():
            summary_content += f"- {language} ({extension})\n"
        
        summary_content += f"\n---\n**Auto-generated by Ashraf Morningstar's Language Generator Bot**\n**GitHub: {self.github_profile}**"
        
        with open(os.path.join(self.base_dir, "SUMMARY.md"), "w", encoding="utf-8") as f:
            f.write(summary_content)

def main():
    """Main function to run the bot"""
    print("🤖 Programming Language File Generator Bot")
    print("==========================================")
    print(f"👨‍💻 Created by: Ashraf Morningstar")
    print(f"🌐 GitHub: https://github.com/AshrafMorningstar")
    print("==========================================\n")
    
    # Create generator instance
    generator = LanguageFileGenerator()
    
    # Create directory structure
    generator.create_base_structure()
    
    # Generate all language files
    generator.create_language_files()
    
    # Generate summary
    generator.generate_summary()
    
    print(f"\n🎊 Generation Complete!")
    print(f"📂 All files saved in: {generator.base_dir}/")
    print(f"📄 Check SUMMARY.md for details")
    print(f"👨‍💻 Credits: Ashraf Morningstar - https://github.com/AshrafMorningstar")
    print("\n🚀 You can now start learning and testing all programming languages!")

if __name__ == "__main__":
    main()