// Java Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

public class JavaTest {
    public static void main(String[] args) {
        System.out.println("Hello from Java!");
        
        // Method call
        String message = helloWorld();
        System.out.println(message);
    }
    
    public static String helloWorld() {
        return "Hello, World!";
    }
}