// Ruby Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

# Simple Ruby example
puts "Hello from Ruby!"

def hello_world
  "Hello, World!"
end

# Method call
message = hello_world
puts message