// Modula-2 Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for Modula-2
// File extension: .mod
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Modula-2!");
    return "Hello, World!";
}

// Execute
main_function();