// Nim Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for Nim
// File extension: .nim
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Nim!");
    return "Hello, World!";
}

// Execute
main_function();