// React Native Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// Simple React Native example
console.log("Hello from React Native!");

// Function example
function helloWorld() {
    return "Hello, World!";
}

// Arrow function
const greet = (name) => `Hello, ${name}!`;

// Usage
console.log(helloWorld());
console.log(greet("Developer"));