// Microsoft Developer Studio Project Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for Microsoft Developer Studio Project
// File extension: .dsp
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Microsoft Developer Studio Project!");
    return "Hello, World!";
}

// Execute
main_function();