/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

-- PLpgSQL Test File
-- Auto-generated by Ashraf Morningstar
-- GitHub: https://github.com/AshrafMorningstar
-- Created: 2025-11-13 16:43:20

-- Simple SQL example
SELECT 'Hello from PLpgSQL!' AS greeting;

-- Create a simple table example
/*
CREATE TABLE test_table (
    id INT PRIMARY KEY,
    name VARCHAR(50)
);
*/