-- SQL Test File
-- Auto-generated by Ashraf Morningstar
-- GitHub: https://github.com/AshrafMorningstar
-- Created: 2025-11-13 16:43:20

-- Simple SQL example
SELECT 'Hello from SQL!' AS greeting;

-- Create a simple table example
/*
CREATE TABLE test_table (
    id INT PRIMARY KEY,
    name VARCHAR(50)
);
*/