<?php
/**
 * PHP Test File
 * Auto-generated by Ashraf Morningstar
 * GitHub: https://github.com/AshrafMorningstar
 * Created: 2025-11-13 16:43:20
 */

echo "Hello from PHP!\n";

function helloWorld() {
    return "Hello, World!";
}

// Function call
$message = helloWorld();
echo $message . "\n";

?>