// SourcePawn Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for SourcePawn
// File extension: .sp
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from SourcePawn!");
    return "Hello, World!";
}

// Execute
main_function();