// DirectX 3D File Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for DirectX 3D File
// File extension: .x
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from DirectX 3D File!");
    return "Hello, World!";
}

// Execute
main_function();