// Ren'Py Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for Ren'Py
// File extension: .rpy
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Ren'Py!");
    return "Hello, World!";
}

// Execute
main_function();