// Open Policy Agent Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for Open Policy Agent
// File extension: .rego
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Open Policy Agent!");
    return "Hello, World!";
}

// Execute
main_function();