"""Python Test File
Auto-generated by Ashraf Morningstar
GitHub: https://github.com/AshrafMorningstar
Created: 2025-11-13 16:43:20
"""

print("Hello from Python!")

# Basic function example
def hello_world():
    return "Hello, World!"

# Main execution
if __name__ == "__main__":
    print(hello_world())