#!/bin/bash
# Bash Test File
# Auto-generated by Ashraf Morningstar
# GitHub: https://github.com/AshrafMorningstar
# Created: 2025-11-13 16:43:20

echo "Hello from Bash!"

hello_world() {
    echo "Hello, World!"
}

# Function call
hello_world