// M4Sugar Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for M4Sugar
// File extension: .m4
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from M4Sugar!");
    return "Hello, World!";
}

// Execute
main_function();