// 4D Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// This is a test file for 4D
// File extension: .4dm
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from 4D!");
    return "Hello, World!";
}

// Execute
main_function();