// TypeScript Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 16:43:20

// TypeScript example
console.log("Hello from TypeScript!");

function helloWorld(): string {
    return "Hello, World!";
}

const greet = (name: string): string => `Hello, ${name}!`;

// Usage
console.log(helloWorld());
console.log(greet("TypeScript Developer"));