/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

// Java Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

public class JavaTest {
    public static void main(String[] args) {
        System.out.println("Hello from Java!");
        
        // Method call
        String message = helloWorld();
        System.out.println(message);
    }
    
    public static String helloWorld() {
        return "Hello, World!";
    }
}