// Unified Parallel C Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:46

// This is a test file for Unified Parallel C
// File extension: .upc
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Unified Parallel C!");
    return "Hello, World!";
}

// Execute
main_function();