// Rust Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

fn main() {
    println!("Hello from Rust!");
    println!("{}", hello_world());
}

fn hello_world() -> &'static str {
    "Hello, World!"
}