// C++ Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

#include <iostream>
#include <string>

using namespace std;

string helloWorld() {
    return "Hello, World!";
}

int main() {
    cout << "Hello from C++!" << endl;
    cout << helloWorld() << endl;
    return 0;
}