// Wollok Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:46

// This is a test file for Wollok
// File extension: .wlk
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Wollok!");
    return "Hello, World!";
}

// Execute
main_function();