/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

"""Jython Test File
Auto-generated by Ashraf Morningstar
GitHub: https://github.com/AshrafMorningstar
Created: 2025-11-13 23:36:45
"""

print("Hello from Jython!")

# Basic function example
def hello_world():
    return "Hello, World!"

# Main execution
if __name__ == "__main__":
    print(hello_world())