// M4 Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:45

// This is a test file for M4
// File extension: .m4
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from M4!");
    return "Hello, World!";
}

// Execute
main_function();