// Jasmine Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:45

// Simple Jasmine example
console.log("Hello from Jasmine!");

// Function example
function helloWorld() {
    return "Hello, World!";
}

// Arrow function
const greet = (name) => `Hello, ${name}!`;

// Usage
console.log(helloWorld());
console.log(greet("Developer"));