// INTERCAL Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

// This is a test file for INTERCAL
// File extension: .i
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from INTERCAL!");
    return "Hello, World!";
}

// Execute
main_function();