// Unity Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

using System;

namespace UnityTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello from Unity!");
            Console.WriteLine(HelloWorld());
        }
        
        static string HelloWorld()
        {
            return "Hello, World!";
        }
    }
}