// OCaml Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

// This is a test file for OCaml
// File extension: .ml
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from OCaml!");
    return "Hello, World!";
}

// Execute
main_function();