// Csound Score Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:45

// This is a test file for Csound Score
// File extension: .sco
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Csound Score!");
    return "Hello, World!";
}

// Execute
main_function();