// OpenCL Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:46

// This is a test file for OpenCL
// File extension: .cl
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from OpenCL!");
    return "Hello, World!";
}

// Execute
main_function();