/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

// Unreal Engine Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

#include <iostream>
#include <string>

using namespace std;

string helloWorld() {
    return "Hello, World!";
}

int main() {
    cout << "Hello from Unreal Engine!" << endl;
    cout << helloWorld() << endl;
    return 0;
}