// Game Maker Language Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:45

// This is a test file for Game Maker Language
// File extension: .gml
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Game Maker Language!");
    return "Hello, World!";
}

// Execute
main_function();