// P4 Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:46

// This is a test file for P4
// File extension: .p4
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from P4!");
    return "Hello, World!";
}

// Execute
main_function();