// Go Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

package main

import "fmt"

func helloWorld() string {
    return "Hello, World!"
}

func main() {
    fmt.Println("Hello from Go!")
    fmt.Println(helloWorld())
}