// DIGITAL Command Language Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:45

// This is a test file for DIGITAL Command Language
// File extension: .com
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from DIGITAL Command Language!");
    return "Hello, World!";
}

// Execute
main_function();