// Zeek Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:46

// This is a test file for Zeek
// File extension: .zeek
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Zeek!");
    return "Hello, World!";
}

// Execute
main_function();