// IGOR Pro Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:45

// This is a test file for IGOR Pro
// File extension: .ipf
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from IGOR Pro!");
    return "Hello, World!";
}

// Execute
main_function();