-- PLSQL Test File
-- Auto-generated by Ashraf Morningstar
-- GitHub: https://github.com/AshrafMorningstar
-- Created: 2025-11-13 23:36:46

-- Simple SQL example
SELECT 'Hello from PLSQL!' AS greeting;

-- Create a simple table example
/*
CREATE TABLE test_table (
    id INT PRIMARY KEY,
    name VARCHAR(50)
);
*/