/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

// JavaScript Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:44

// Simple JavaScript example
console.log("Hello from JavaScript!");

// Function example
function helloWorld() {
    return "Hello, World!";
}

// Arrow function
const greet = (name) => `Hello, ${name}!`;

// Usage
console.log(helloWorld());
console.log(greet("Developer"));