// Modula-3 Test File
// Auto-generated by Ashraf Morningstar
// GitHub: https://github.com/AshrafMorningstar
// Created: 2025-11-13 23:36:45

// This is a test file for Modula-3
// File extension: .m3
// Auto-generated by Ashraf Morningstar

main_function() {
    print("Hello from Modula-3!");
    return "Hello, World!";
}

// Execute
main_function();